Repository Husky-Coding-Project/huskyreads, pull requests merged in 2022-06, with the labels that each got.

#151 148 update books primary key
  back-end/API_Documentation/Books.md
  back-end/API_Documentation/Bookshelves.md
  back-end/app/tests/book/detail_book.test.js
  back-end/app/tests/book/search_book.test.js
  back-end/app/tests/bookshelf/book_bookshelf.test.js
  back-end/app/tests/bookshelf/get_bookshelf.test.js
  back-end/app/tests/resetdb.sql
  back-end/scripts/database.sql
Labels: documentation, enhancement

#150 Updated ISBN handling
  back-end/scripts/importJsonToDatabase.py
Labels: enhancement

#154 Changed some wording and spelling. Added URL
  README.md
Labels: documentation
